# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/angelonutu/Desktop/ADA2.0/Progetto-Finale-ADA/master/master.srcs/sources_1/ip/floating_point_2/floating_point_2.xci
# IP: The module: 'floating_point_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/angelonutu/Desktop/ADA2.0/Progetto-Finale-ADA/master/master.gen/sources_1/ip/floating_point_2/floating_point_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/angelonutu/Desktop/ADA2.0/Progetto-Finale-ADA/master/master.srcs/sources_1/ip/floating_point_2/floating_point_2.xci
# IP: The module: 'floating_point_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/angelonutu/Desktop/ADA2.0/Progetto-Finale-ADA/master/master.gen/sources_1/ip/floating_point_2/floating_point_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
